name: Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore App

      - name: Build
        run: dotnet build --no-restore App
      
      - name: Publish build output
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: |
            ./App/bin/
            ./App/**/bin/
            ./App/**/obj/

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore App

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-output

      - name: Run Tests
        run: dotnet test --no-build --verbosity normal Tests

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore App

      - name: Check code formatting
        run: dotnet format --verify-no-changes App

      - name: Read secret
        run: echo "Secret value is ${{ secrets.MY_SECRET }}"

  secret:
    name: Read fake secret
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Read secret
        run: echo "Secret value is ${{ secrets.MY_SECRET }}"